[phx]
port = 4000
ip = "127.0.0.1"
secret_key = "txlMOtlaY5x3crvOCko4uV5PM29ul3zGo1oBGNO3cDXx+7GHLKqt0gR9qzgThxb5"
url_host_prefix = ""
static_url_host_prefix = ""
admin_access_key = ""

[guardian]
secret_key = "txlMOtlaY5x3crvOCko4uV5PM29ul3zGo1oBGNO3cDXx+7GHLKqt0gR9qzgThxb5"

[erlang]
node_cookie = "txlMOtlaY5x3crvOCko4uV5PM29ul3zGo1oBGNO3cDXx+7GHLKqt0gR9qzgThxb5"

[habitat]
ip = "127.0.0.1"
http_port = 9631

[oauth_google]
client_id = "foo"
client_secret = "bar"

[db]
username = "admin"
password = "admin"
hostname = "localhost"
database = "ret_dev"
template = "template0"
pool_size = 16

[security]
content_security_policy = "default-src 'self'"
cors_origins = "[\"*\"]"

[pages]
insecure_ssl = "false"
